### ISSUE TITLE
Regression: sdocs no longer work in strongloop/loopback

### ISSUE THREAD

**Issue by bajtos** [strongloop/strong-docs#87]
```
$ git clone git@github.com:strongloop/loopback.git
$ cd loopback
$ sdocs -p
Preview your docs @ http://localhost:3000

Refresh your browser to rebuild.
```

Load the page in the browser and observe sdocs crashing with the following error:

```
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { title: 'Base models', depth: 2 }
    at assertPath (path.js:28:11)
    at Object.extname (path.js:1452:5)
    at Docs.<anonymous> (/usr/local/lib/node_modules/strong-docs/lib/docs.js:162:16)
    at Array.forEach (native)
    at Docs.<anonymous> (/usr/local/lib/node_modules/strong-docs/lib/docs.js:161:18)
    at emitNone (events.js:105:13)
    at TaskEmitter.emit (events.js:207:7)
    at TaskEmitter.<anonymous> (/usr/local/lib/node_modules/strong-docs/node_modules/strong-task-emitter/lib/task-emitter.js:83:14)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

The problem was introduced in version 1.3.0, the version 1.2.0 works correctly.

**Comment by bajtos** [comment]
Fixed in `strong-docs@1.3.1`
